---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-pre-install
  annotations:
    helm.sh/hook: pre-install
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-post-install
  annotations:
    helm.sh/hook: post-install
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-pre-upgrade
  annotations:
    helm.sh/hook: pre-upgrade
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-post-upgrade
  annotations:
    helm.sh/hook: post-upgrade