---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-pre-install
  annotations:
    helm.sh/hook: pre-install
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-post-install
  annotations:
    helm.sh/hook: post-install
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-pre-upgrade
  annotations:
    helm.sh/hook: pre-upgrade
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-post-upgrade
  annotations:
    helm.sh/hook: post-upgrade
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-pre-install-upgrade
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-post-install-upgrade
  annotations:
    helm.sh/hook: post-install,post-upgrade
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-post-install-d
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ .Release.Name }}-post-install-{{ .Release.Revision }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/resource-policy: keep